# Generated by Django 5.2.5 on 2025-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='accessories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
